### ISSUE TITLE
Ask some questions

### ISSUE THREAD

**Issue by YifengZhaoo** [deepmodeling-activity/hackathon-test-cases#1]
1. It seems that the installation of Packmol requires gfortran, at least in my case. So, should the compilation steps be as follows?

```
sudo apt-get install gfortran
tar -xvzf packmol-20.14.2.tar.gz
cd packmol
make
```
Please confirm whether this is correct. Never use this package before. 

2. How can I test my implementation using your example?
I noticed there is a test case available where I can incorporate my implementation. However, how can I obtain accuracy and performance scores?

**Comment by Roy-Kid** [comment]
For question 1 : Yes, you should install gfortran first. I forget to write down this because I always install those essentials after installing the OS.

About Q2, you can not test it for now by using our tools. Because the profiling and scoring platform is provided by Peking University supercomputing team and they are working on the backend. You can test it on your own PC and if you have very urgent requirement(ARM CPU or GPU), you can directly ask organizer in the WeiXin group.

**Comment by YifengZhaoo** [comment]
Thanks.
